name = "ely-browser-cloud"
main = "src/index.ts"
compatibility_date = "2026-05-08"
compatibility_flags = ["nodejs_als"]

[[d1_databases]]
binding = "ELY_DB"
database_name = "elydora-db"
database_id = "6cf37748-b5ff-4765-ba91-69f3780dcbd7"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "ELY_STORAGE"
bucket_name = "ely-browser-storage"

[[kv_namespaces]]
binding = "ELY_KV"
id = "5eff92ba31c94fcf83e1b6d5e79ce070"

[vars]
ELY_ENVIRONMENT = "local"
ELY_AUTH_BASE_URL = "http://localhost:8787"

[[analytics_engine_datasets]]
binding = "ELY_API_AUDIT"
dataset = "ely_api_audit"

[[analytics_engine_datasets]]
binding = "ELY_DIAGNOSTICS"
dataset = "ely_diagnostics"

[[ratelimits]]
name = "ELY_RATE_LIMITER"
namespace_id = "1001"

  [ratelimits.simple]
  limit = 600
  period = 60
